baseURL = "https://dalo1.netlify.app/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Aafu theme"
    author = "Darshan Baral"
    description = "Website title"
    copyright = "DLn"

    [params.theme]
        # Available themes are 'lght', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "David Lowén, DLn."
		tagline = "Problem solver"
		location = "Stockholm, Swe"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/david-lowen/"
            title = "LinkedIn"		
       # [[params.social.list]]
        #    class = "fab"
         #   icon = "fa-stack-overflow"
          #  url = "#"
           # title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/dalo1741"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "#"
            title = "Twitter"
	#	[[params.social.list]]
   #         class = "ai"
    #        icon = "ai-google-scholar"
     #       url = "#"
      #      title = "Google Scholar"
	#	[[params.social.list]]
   #         class = "ai"
    #        icon = "ai-researchgate"
     #       url = "#"
      #      title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**Highly ambitous and curious**, love to make things run smooth and believe that everything that can be automated should be. Also, hugh intrest in *finance*, *digitalization*, *family and friends*."
        
    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Controller/Senior Accountant"
            dates = "Aug 2020 - *Present*"
            link = "https://www.klarna.com/"
            company = "Klarna Bank AB"
            details = "Work with process optimzation related to financial reporting. Moreover, projectleader of Klarna AB's audit process. This position carries many parameters of flexibility in order to direct my knowledge in areas most needed.This position mainly focus on problem solving both short-term and more long-term in form of looking over and **adjust/improve** current processes within Klarna Bank."
        [[params.experience.list]]
            position = "Audit associate Financial services"
            dates = "Aug 2018 - Aug 2020"
            link = "https://home.kpmg/se"
            company="KPMG AB"
            details = "As an Audit Associate at Financial Services I work in a team, daily offering auditing and consulting towards firms in the Financial Sector. That includes primarily identifying risks and opportunities through interviewing key personnel, examining company specific processes or to perform extensive data-analytics on figures and financial reports. The role offers constantly new challenges, business models and exciting meetings."
        [[params.experience.list]]
            position = "Accountant associate"
            dates = "Oct 2016 - Aug 2018"
            link = "https://www.ncc.se/investor-relations/finansiell-information/ncc-treasury/"
            company = "NCC Treasury AB "
            details = "The role was part time during my University Studies. At NCC Treasury, I worked in a small team and were primarly hired to support the middle office team during interim reporting periods and vacation periods. The position offered tasks primarly related to preparation of financial reporting, cash-management, risk-analysis, financial instruments, accounting and book-keeping."
        [[params.experience.list]]
            position = "Balance Control Manager"
            dates = "Jun 2016 - Aug 2016"
            link = "https://www.volvotrucks.se/"
            company = "Volvo Trucks AB"
            details = "Summer internship att Volvo Logistics. The position offered tasks in Supply Chain Management focusing on optimizing suppliers usages of Volvo packaging. Major tasks included communication with suppliers within the EMEA-region, data-analysis, planning inventories and support."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Master degree Accounting & Financial management"
            college = "Uppsala University, Uppsala"
            dates = "2017 - 2018"
            thesis_title = "Dividend yield strategies in Sweden"
            thesis_link = "http://uu.diva-portal.org/smash/get/diva2:1222733/FULLTEXT01.pdf"
        [[params.education.list]]
            degree = "M.S. in Business & Economics"
            college = "Uppsala University & Swedish agricultural university, Uppsala"
            dates = "2013 - 2017"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_link = "#"
        [[params.education.list]]
            degree = "Exchange studies in economics"
            college = "University of British Columbia, Vancouver Canada"
            dates = "2015 - 2016"

    # Publication section
   # [params.publication]
    #    title = "Publications"
     #   icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
      #  format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
       # types = ["Journal Articles", "Proceedings"]

        #[[params.publication.list]]
         #   title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
          #  authors = "F Last, F Second, P secondary"
           # date = "2018"
            #journal = "Journal of Field 52 (16), 9033-9044"
            #link = "#"
            #type = "Journal Articles"

   
    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Excel programming, JournalEntries tool to convert Visma .SIE files directly to a suitable excel list"
            url = "#"
            description = "Creating a tool to manipulate the .SIE format used by certain accounting tools for journal entries lists. By integrating PowerQuery and some VBA programming. By using this tool one step is removed one avoid the need of an accounting tool when converting these file to a desired list format."
        [[params.project.list]]
            title = "Balancesheet reconciliation tool using VBA"
            url = "#"
            description = "Project uses simple VBA programming to simplify the reconciliation process the tool is also adapted to **analysis for office** which enables direct connection to the accounting software SAP. Purpose of this tool serves to speed up the process and semiautomate the reconciliation of Balancesheet acocunts."
   
    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Date software: Excel, PowerQuery"
            skillrating = 95
        [[params.skill.list]]
            skill = "Accounting software: SAP,Fortnox"
            skillrating = 80
        [[params.skill.list]]
            skill = "Programming, Rstudio, VBA"
            skillrating = 50
        [[params.skill.list]]
            skill = "Programming, SQL, Phyton"
            skillrating = 40
    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
		    [[params.hobby.list]]		
		    hobby = "Stock market."
		     [[params.hobby.list]]		
		    hobby = "Programming."
        [[params.hobby.list]]		
		    hobby = "Running."
        [[params.hobby.list]]		
		    hobby = "Hiking."
        [[params.hobby.list]]		
		    hobby = "Cross-country skiing."
		    [[params.hobby.list]]		
		    hobby = "Snowboarding."
		    [[params.hobby.list]]		
		    hobby = "Friends and family."
